#!/usr/bin/env bash

# Colour Pallete: https://i.sstatic.net/e63et.png

set_style() {
  local session=$1 bg=$2 fg=${3:-}
  tmux set -t "$session" status-bg "$bg"
  [ -n "$fg" ] && tmux set -t "$session" status-fg "$fg"
}

# Function to attach to session, or switch to if already inside tmux
attach_or_switch() {
  local session=$1
  if [ -n "$TMUX" ]; then
    tmux switch-client -t "$session"
  else
    tmux attach -t "$session"
  fi
}

if [ -n "$1" ]; then
  choice="$1"
else
  echo "Select a session to open:"
  echo "  1) k3"
  echo "  2) notes"
  echo "  3) config"
  echo "  3) miscellaneous"
  read -rp "Enter choice [1-3]: " choice
fi

case "$choice" in
  1|k3)                 SESSION="k3" ;;
  1|kowhai)             SESSION="kowhai" ;;
  2|notes)              SESSION="notes" ;;
  3|config)             SESSION="config" ;;
  4|misc|miscellaneous) SESSION="misc" ;;
  *)
    echo "Invalid choice: $choice"
    exit 1
    ;;
esac

# Attach if session already exists
tmux has-session -t "$SESSION" 2>/dev/null
if [ $? -eq 0 ]; then
  echo "Switching to existing session: $SESSION"
  attach_or_switch "$SESSION"
  exit 0
fi

case "$SESSION" in
  k3)
    tmux new-session -d -s "$SESSION" -n 'servers' -c ~/src/kogan/K3/
    set_style "$SESSION" colour4 colour0

    # Pane 1: node server
    tmux send-keys -t "$SESSION:1.0" 'cd k4 && npm run dev:au' C-m

    # Pane 2: k3 server
    tmux split-window -h -t "$SESSION:1" -c ~/src/kogan/K3
    tmux send-keys -t "$SESSION:1.1" './dev_setup.sh service_up && ./shortcuts.sh start_k3' C-m

    # Window 2: venv
    tmux new-window -t "$SESSION:2" -n 'venv' -c ~/src/kogan/K3
    tmux send-keys -t "$SESSION:2" 'source .venv/bin/activate' C-m
    ;;
  kowhai)
    tmux new-session -d -s "$SESSION" -n 'servers' -c ~/src/kogan/Kowhai/
    set_style "$SESSION" colour147 colour0

    # Pane 1: node server
    tmux send-keys -t "$SESSION:1.0" 'cd frontend && yarn run dev' C-m

    # Pane 2: k3 server
    tmux split-window -h -t "$SESSION:1" -c ~/src/kogan/Kowhai/
    tmux send-keys -t "$SESSION:1.1" 'dc up django' C-m

    # Window 2: venv
    tmux new-window -t "$SESSION:2" -n 'venv' -c ~/src/kogan/Kowhai/
    tmux send-keys -t "$SESSION:2" 'source .venv/bin/activate' C-m
    ;;

  notes)
    tmux new-session -d -s "$SESSION" -n 'notes' -c ~/src/jasperRob/notes/
    set_style "$SESSION" colour5 colour0
    ;;

  config)
    tmux new-session -d -s "$SESSION" -n 'config' -c ~/
    set_style "$SESSION" colour209 colour0
    ;;

  misc)
    tmux new-session -d -s "$SESSION" -n 'misc' -c ~/misc/
    set_style "$SESSION" colour2 colour0
    ;;
esac

# Attach or switch to the session
attach_or_switch "$SESSION"
